// ReactJS/TeamWorkAutoShop/client-autoshop/auto-shop/src/components/reviews/Review.js
import React from 'react'

export default class Review extends React.Component {
  render () {
    let review = this.props.review
    return (
      <div className='single-review row'>
        <div className='col-sm-3 left-review'>
          <div>
            {review.author.username}
          </div>
          <div>
            {new Date(review.date).toLocaleDateString()}
          </div>
          <div className={`review-rating review-rating-${review.rating}`} />
        </div>
        <div className='col-sm-9 right-review'>
          {review.text}
        </div>
      </div>
    )
  }
}

// Angular2/TeamWork/client/src/app/reviews/review.component.ts
import { Component, Input } from '@angular/core';

import { Review } from './review';

@Component({
    selector: 'review',
    templateUrl: './review.component.html',
    styleUrls:['./review.component.css']
})

export class ReviewComponent {
    @Input() review: Review;
}
<div class='single-review row'>
    <div class='col-sm-3 left-review'>
        <div>
            {{review.author.username}}
        </div>
        <div>
            {{review.date}}
        </div>
        <div class='review-rating review-rating-{{review.rating}}'></div>
    </div>
    <div class='col-sm-9 right-review'>
        {{review.text}}
    </div>
</div>
